import type { AnalysisResult } from "@backend/types";

export function exportToJson(result: AnalysisResult): void {
  const json = JSON.stringify(result, null, 2);
  const blob = new Blob([json], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `signalx-${result.startup.name.toLowerCase().replace(/\s+/g, "-")}-${Date.now()}.json`;
  a.click();
  URL.revokeObjectURL(url);
}

export function exportToMarkdown(result: AnalysisResult): void {
  const md = `# SignalX AI — ${result.startup.name} Intelligence Report

> Generated: ${new Date(result.createdAt).toLocaleString()}
> URL: ${result.startup.url}

---

## 📊 Executive Summary

${result.insights.summary}

**Opportunity Score:** ${result.insights.opportunityScore}/100
**Confidence:** ${result.insights.confidenceScore}%

---

## 🎯 Ideal Customer Profile

${result.insights.icp.map((icp, i) => `${i + 1}. ${icp}`).join("\n")}

---

## 💡 Value Proposition

${result.insights.valueProposition}

---

## 💰 Pricing Analysis

**Model:** ${result.pricing.model}
**Avg Price:** ${result.pricing.averagePrice || "N/A"}

${result.pricing.tiers.map((t) => `### ${t.name} — ${t.price}${t.period ? `/${t.period}` : ""}
${t.features.map((f) => `- ${f}`).join("\n")}`).join("\n\n")}

---

## 🏆 Competitive Landscape

${result.competitors.map((c) => `### ${c.name} (${c.url})
${c.description}

**Strengths:** ${c.strengths.join(", ")}
**Weaknesses:** ${c.weaknesses.join(", ")}
**Similarity:** ${c.similarityScore}%`).join("\n\n")}

---

## 🔍 Market Gaps

${result.marketGaps.map((g) => `### ${g.title}
${g.description}

**Opportunity:** ${g.opportunity}
**Impact:** ${g.impact} | **Difficulty:** ${g.difficulty}`).join("\n\n")}

---

## ✅ Feature Coverage

${result.features.map((f) => `- [${f.hasIt ? "x" : " "}] ${f.feature}${f.notes ? ` — *${f.notes}*` : ""}`).join("\n")}

---

## 🚀 Actionable Insights

${result.insights.actionableInsights.map((a, i) => `${i + 1}. ${a}`).join("\n")}

---

*Report generated by SignalX AI — Powered by Anakin APIs & Gemini AI*
`;

  const blob = new Blob([md], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `signalx-${result.startup.name.toLowerCase().replace(/\s+/g, "-")}-${Date.now()}.md`;
  a.click();
  URL.revokeObjectURL(url);
}
